import React from "react";

export function Home () {
  return (
    <div>
      <p>userName - <span>LOGOUT</span> - SHOW/HIDE HINTS</p>
      <br/>
      <p>Current Game/Map</p>
      <p>- - here is the currently displayed game or map, with its associated play tab and chat tab </p>
      <p>- - whether it is a game you are hosting, a game you are playing in, or a map in creation, the same TYPE of object is accessed</p>
      <p>- - the only difference is the tools/actions displayed</p>
      <p>- game/map - name - status</p>
      <br/>
      <p>Games - <span>JOIN GAME - </span> <span>NEW GAME</span> </p>
      <p>- - Selecting JOIN GAME gives you the option to "Enter Secret Key: "</p>
      <p>- - - this is how you join a game by invitation; the secret key has to be shared outside this platform</p>
      <p>- - - also the host would have had to add your username to a list of invitees</p>
      <p>- - - two way factor identification</p>
      <p>- - - if there is no secret key, you will be given the option to join a random game</p>
      <p>- - - if there is no random game available, you will be placed in a zombies map</p>
      <p>- - Selecting NEW GAME gives you the option to either create a NEW MAP or CHOOSE MAP from saved boardTemplates</p>
      <p>- game - name - status</p>
      <p>- game - name - status</p>
      <p>- game - name - status</p>
      <br/>
      <p>Maps i.e. boardTemplates - <span>NEW MAP</span></p>
      <p>- map - name</p>
      <p>- map - name</p>
      <p>- map - name</p>
      <br/>
      <br/>
      <p>Characters - <span>NEW CHAR</span> - unique creatures</p>
      <p>Monsters - <span>NEW MONSTER</span> - generic creature classes/types - could have many, stats are generated by preset parameters, i.e. CR</p>
      <br/>
      <br/>
      <p>Items - <span>NEW ITEM</span></p>
      <p>Abilities - <span>NEW ABILITY</span></p>
      <p>- - item, ability, action === EFFECT</p>
      <br/>
    </div>
  )
}